CREATE DATABASE SHIRKET

USE SHIRKET

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR(50)
)

CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
MKOD NVARCHAR(50) NOT NULL,
SAA NVARCHAR(255) NOT NULL,
VEZIFEID INT REFERENCES VEZIFE(ID),
SALARY MONEY
)

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR(50) NOT NULL
)

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
BUYPRICE MONEY,
SELLPRICE MONEY
)

CREATE TABLE SATISH(
ID INT PRIMARY KEY IDENTITY,
MEHSULID INT REFERENCES MEHSUL(ID),
ISCIID INT REFERENCES ISCI(ID),
FILIALID INT REFERENCES FILIAL(ID),
ENDIRIM FLOAT,
TARIX DATE
)

INSERT INTO VEZIFE
VALUES('KASSIR')

INSERT INTO FILIAL
VALUES('AXMEDLI')

INSERT INTO MEHSUL
VALUES('COKE',5,10)

INSERT INTO ISCI
VALUES('OBA','QAQA QAQAYEV QAQALAR OGLU' , 1 , 120)

SELECT COUNT(ISCI.ID) 'EMPLOYEE COUNT' FROM ISCI 

SELECT ISCI.SAA,ISCI.SALARY FROM ISCI
ORDER BY SALARY DESC

SELECT BUYPRICE FROM MEHSUL
ORDER BY BUYPRICE DESC

SELECT * FROM SATISH
ORDER BY TARIX ASC

SELECT CONCAT(ISCI.SAA,' ',VEZIFE.VEZIFE) 'ISCI VE VEZIFELERI' FROM ISCI
JOIN VEZIFE
ON ISCI.VEZIFEID = VEZIFE.ID

SELECT ISCI.SAA,FILIAL.FILIAL,MEHSUL.NAME 'MEHSUL',MEHSUL.BUYPRICE,MEHSUL.SELLPRICE,SATISH.ENDIRIM FROM SATISH
JOIN ISCI
ON SATISH.ISCIID = ISCI.ID
JOIN FILIAL
ON SATISH.FILIALID = FILIAL.ID
JOIN MEHSUL
ON SATISH.MEHSULID = MEHSUL.ID


SELECT SUM(MEHSUL.SELLPRICE) - SUM(SATISH.ENDIRIM) 'OBSHI' FROM MEHSUL
JOIN SATISH
ON MEHSUL.ID = SATISH.MEHSULID

SELECT SUM(MEHSUL.SELLPRICE) - SUM(SATISH.ENDIRIM) 'OBSHI' FROM MEHSUL
JOIN SATISH
ON MEHSUL.ID = SATISH.MEHSULID
WHERE DATEPART(MM,SATISH.TARIX) = MONTH(GETDATE()) AND DATEPART(YY,SATISH.TARIX) = YEAR(GETDATE())

SELECT SUM(MEHSUL.SELLPRICE) - SUM(SATISH.ENDIRIM) - SUM(MEHSUL.BUYPRICE) 'OBSHI' FROM MEHSUL
JOIN SATISH
ON MEHSUL.ID = SATISH.MEHSULID
WHERE DATEPART(MM,SATISH.TARIX) = MONTH(GETDATE()) AND DATEPART(YY,SATISH.TARIX) = YEAR(GETDATE())

SELECT ISCI.SAA , COUNT(SATISH.ISCIID) 'SAY' FROM ISCI
JOIN SATISH
ON ISCI.ID = SATISH.ISCIID
WHERE DATEPART(MM,SATISH.TARIX) = MONTH(GETDATE()) AND DATEPART(YY,SATISH.TARIX) = YEAR(GETDATE())
GROUP BY ISCI.SAA
HAVING COUNT(ISCI.SAA)>=0

SELECT ISCI.SAA , SUM(MEHSUL.SELLPRICE) 'YEKUN' FROM ISCI
JOIN SATISH
ON ISCI.ID = SATISH.ISCIID
JOIN MEHSUL 
ON SATISH.MEHSULID = MEHSUL.ID
WHERE DATEPART(MM,SATISH.TARIX) = MONTH(GETDATE()) AND DATEPART(YY,SATISH.TARIX) = YEAR(GETDATE())
GROUP BY ISCI.SAA
HAVING COUNT(ISCI.SAA)>=0

SELECT ISCI.SAA , SUM(MEHSUL.SELLPRICE) - SUM(MEHSUL.BUYPRICE) 'YEKUN' FROM ISCI
JOIN SATISH
ON ISCI.ID = SATISH.ISCIID
JOIN MEHSUL 
ON SATISH.MEHSULID = MEHSUL.ID
WHERE DATEPART(MM,SATISH.TARIX) = MONTH(GETDATE()) AND DATEPART(YY,SATISH.TARIX) = YEAR(GETDATE())
GROUP BY ISCI.SAA
HAVING COUNT(ISCI.SAA)>=0

SELECT FILIAL.FILIAL , SUM(MEHSUL.SELLPRICE) - SUM(MEHSUL.BUYPRICE) 'GELIR' FROM FILIAL
JOIN SATISH
ON SATISH.FILIALID = FILIAL.ID
JOIN MEHSUL
ON SATISH.MEHSULID = MEHSUL.ID
WHERE SATISH.TARIX = GETDATE() 
GROUP BY FILIAL.FILIAL
HAVING COUNT(FILIAL.FILIAL) >= 0

SELECT MEHSUL.NAME , COUNT(SATISH.MEHSULID) FROM MEHSUL
JOIN SATISH
ON MEHSUL.ID = SATISH.MEHSULID
WHERE DATEPART(MM,SATISH.TARIX) = MONTH(GETDATE()) AND DATEPART(YY,SATISH.TARIX) = YEAR(GETDATE())
GROUP BY MEHSUL.NAME
HAVING COUNT(MEHSUL.NAME) > 0

SELECT MEHSUL.NAME , COUNT(SATISH.MEHSULID) 'SAY' FROM MEHSUL
JOIN SATISH
ON MEHSUL.ID = SATISH.MEHSULID
WHERE DATEPART(MM,SATISH.TARIX) = MONTH(GETDATE()) AND DATEPART(YY,SATISH.TARIX) = YEAR(GETDATE())
GROUP BY MEHSUL.NAME
HAVING COUNT(MEHSUL.NAME) > 0






